resolver: lts-15.11
packages:
- Core
- Editor
- Grammar
- Label
- Lispy
- Parser
- Printer
- Repl/Lib
- Repl/Terminal
extra-deps:
- git: https://github.com/syallop/Reversible
  commit: 84188a89af962716dc0534d552da715305cb0cf5
- git: https://github.com/syallop/DSL-Compose
  commit: 5a95ae855f3291aa3193a7424892035226b10d2f
- hedgehog-quickcheck-0.1.1
- brick-0.46
- config-ini-0.2.4.0
- data-clist-0.1.2.2
- text-zipper-0.10.1
- word-wrap-0.4.1
- megaparsec-8.0.0
- parser-combinators-1.0.1
- pretty-tree-0.1.0.0@sha256:49b0e17008f9d30328db2bcc2958f3a7b78d154d2335c2dbaa2073e237b524ae
allow-newer: true
extra-package-dbs: []

